<#
.SYNOPSIS
    Reads HandBrakeQueue.csv and transcodes every listed video with HandBrakeCLI.

.DESCRIPTION
    * Reads the CSV generated by Scan-MediaInfo.ps1.
    * Executes HandBrakeCLI with the chosen codec (H.265 by default).
    * Writes a progress bar and periodic status messages.
    * Persists a JSON status file (HandBrakeStatus.json) that tracks
      Completed, Failed and Skipped items – enabling safe resume after
      interruption or crash.

.PARAMETER CsvPath
    Full path to the HandBrakeQueue.csv file (default: same folder as script).

.PARAMETER HandBrakePath
    Full path to HandBrakeCLI.exe. If omitted the script tries to locate it
    in the typical install folder and the system PATH.

.PARAMETER DebugCommands
    If specified, prints the exact HandBrakeCLI command before execution.
    Useful for copying and running commands manually for troubleshooting.

.PARAMETER QualityLevel
    Quality-based encoding level (0-51). Lower values = higher quality.
    Default is 18 (near-lossless). Typical range: 16-22.

.PARAMETER UseQSV
    If $true (default), uses Intel QSV hardware acceleration (qsv_h265 or av1_qsv).
    If $false, uses software encoding (x265 or av1).

.EXAMPLE
    .\Run-HandBrakeCLI.ps1 -CsvPath ".\HandBrakeQueue.csv" -HandBrakePath "C:\Program Files\HandBrake\HandBrakeCLI.exe"
    .\Run-HandBrakeCLI.ps1 -CsvPath '.\HandBrakeQueue.csv' -HandBrakePath "V:\HandBrakeCLI-1.11.1-win-x86_64\HandBrakeCLI.exe" -DebugCommands
    . V:\Run-HandBrakeCLI.ps1 -QualityLevel 20 -UseQSV $false
#>
#Requires -Version 7.1

[CmdletBinding()]
param (
    [Parameter(Mandatory=$false)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$CsvPath = (Join-Path $PSScriptRoot 'HandBrakeQueue.csv'),

    [Parameter(Mandatory=$false)]
    [string]$HandBrakePath = $null,

    [Parameter(Mandatory=$false)]
    [switch]$DebugCommands,

    [Parameter(Mandatory=$false)]
    [ValidateRange(0, 51)]
    [int]$QualityLevel = 18,

    [Parameter(Mandatory=$false)]
    [bool]$UseQSV = $true
)

# -------------------------------------------------
# Locate HandBrakeCLI.exe if the caller did not give it
# -------------------------------------------------
function Get-HandBrakePath {
    param([string]$Candidate)

    if ($Candidate -and (Test-Path $Candidate -PathType Leaf)) {
        return $Candidate
    }

    if ($env:HANDBRAKE_CLI_PATH -and (Test-Path $env:HANDBRAKE_CLI_PATH -PathType Leaf)) {
        return $env:HANDBRAKE_CLI_PATH
    }

    if ($env:HANDBRAKE_PATH -and (Test-Path $env:HANDBRAKE_PATH -PathType Leaf)) {
        return $env:HANDBRAKE_PATH
    }
}

# -------------------------------------------------
# Load the queue from a CSV file.
# -------------------------------------------------
function Import-Queue {
    param(
        [string]$CsvPath
    )

    if (-not (Test-Path $CsvPath -PathType Leaf)) {
        throw "Queue file not found: $CsvPath"
    }

    return @(Import-Csv -Path $CsvPath -Encoding UTF8)
}

# -------------------------------------------------
# Load the current processing status from a JSON file.
# Returns an object with Completed, Failed, Skipped, and Retried arrays.
# If the file doesn't exist, returns empty arrays (first run).
# -------------------------------------------------
function Import-Status {
    param(
        [string]$StatusFile
    )

    if (Test-Path $StatusFile -PathType Leaf) {
        try {
            $status = Get-Content -Path $StatusFile -Encoding UTF8 | ConvertFrom-Json
            return @{
                Completed = [System.Collections.ArrayList]($status.Completed)
                Failed    = [System.Collections.ArrayList]($status.Failed)
                Skipped   = [System.Collections.ArrayList]($status.Skipped)
                Retried   = [System.Collections.ArrayList]($status.Retried)
            }
        }
        catch {
            Write-Warning "Failed to load status file: $_. Starting with empty status."
            return @{
                Completed = [System.Collections.ArrayList]@()
                Failed    = [System.Collections.ArrayList]@()
                Skipped   = [System.Collections.ArrayList]@()
                Retried   = [System.Collections.ArrayList]@()
            }
        }
    }
    else {
        # First run – no status file exists yet
        return @{
            Completed = [System.Collections.ArrayList]@()
            Failed    = [System.Collections.ArrayList]@()
            Skipped   = [System.Collections.ArrayList]@()
            Retried   = [System.Collections.ArrayList]@()
        }
    }
}

# -------------------------------------------------
# Save the current processing status to a JSON file, enabling safe resume after interruption.
# -------------------------------------------------
function Save-Status {
    param(
        [string]$StatusFile,
        [System.Collections.ArrayList]$Completed,
        [System.Collections.ArrayList]$Failed,
        [System.Collections.ArrayList]$Skipped,
        [System.Collections.ArrayList]$Retried
    )

    [pscustomobject]@{
        Completed = $Completed
        Failed    = $Failed
        Skipped   = $Skipped
        Retried   = $Retried
    } | ConvertTo-Json -Depth 5 | Set-Content -Path $StatusFile -Encoding UTF8
}

# -------------------------------------------------
# Save the conversions list to a CSV file for cleanup operations.
# Only exports if there are conversions to save.
# -------------------------------------------------
function Save-Conversions {
    param(
        [string]$ConversionsFile,
        [System.Collections.ArrayList]$Conversions
    )

    if ($Conversions.Count -gt 0) {
        $Conversions | Export-Csv -Path $ConversionsFile -NoTypeInformation -Encoding UTF8 -Force
        Write-Host "`n✅ Conversions exported to: $ConversionsFile" -ForegroundColor Green
    }
}

# -------------------------------------------------
# Build HandBrakeCLI arguments for the current queue item.
# Optimizes for fidelity: hardware acceleration, quality-based encoding, 
# metadata/audio/subtitle preservation, and HDR support.
# -------------------------------------------------
function Build-HandBrakeArguments {
    param(
        [string]$Source,
        [string]$Target,
        [string]$DesiredCodec,
        [int]$QualityLevel = 18,
        [bool]$UseQSV = $true
    )

    $hbArgs = @(
        # Container
        '-f', 'av_mkv',
        
        # Input/Output
        '-i', "`"$Source`"",
        '-o', "`"$Target`""
    )

    # ======================================
    # Video Codec Selection
    # ======================================
    if ($UseQSV) {
        # QSV hardware-accelerated encoding
        $hbArgs += '--enable-qsv-decoding'
        
        switch ($DesiredCodec.ToUpperInvariant()) {
            'H.265' { $hbArgs += '-e', 'qsv_h265' }
            'AV1'   { 
                # NOTE: qsv_av1 is available in newer HandBrake nightly/development builds.
                # For stable releases, using svt_av1 (GPU-accelerated) as interim solution.
                # TODO: Switch to 'qsv_av1' once HandBrake stable release includes it.
                $hbArgs += '-e', 'svt_av1'
            }
            default { 
                Write-Warning "Unknown codec '$DesiredCodec' – falling back to qsv_h265."
                $hbArgs += '-e', 'qsv_h265'
            }
        }
    }
    else {
        # Software encoding (fallback)
        switch ($DesiredCodec.ToUpperInvariant()) {
            'H.265' { $hbArgs += '-e', 'x265' }
            'AV1'   { $hbArgs += '-e', 'svt_av1' }  # Hardware-accelerated AV1 fallback
            default { 
                Write-Warning "Unknown codec '$DesiredCodec' – falling back to x265."
                $hbArgs += '-e', 'x265'
            }
        }
    }

    # ======================================
    # Video Quality & Framerate
    # ======================================
    $hbArgs += '-q', $QualityLevel.ToString()     # Quality-based encoding (lower = better)
    $hbArgs += '--vfr'                            # Preserve variable framerate

    # ======================================
    # Picture & Color Preservation
    # ======================================
    $hbArgs += '--crop-mode', 'none'              # Disable automatic black bar cropping
    $hbArgs += '--keep-display-aspect'            # Preserve display aspect ratio
    $hbArgs += '--color-range', 'auto'            # Auto-detect color range
    $hbArgs += '-M', 'auto'                       # Auto-detect matrix
    $hbArgs += '--hdr-dynamic-metadata', 'all'    # Preserve HDR10+ and Dolby Vision

    # ======================================
    # Container & Metadata
    # ======================================
    $hbArgs += '--keep-metadata'                  # Preserve title, date, etc.
    $hbArgs += '-m'                               # Preserve chapter markers

    # ======================================
    # Audio Preservation
    # ======================================
    $hbArgs += '--all-audio'                      # Select every audio track
    $hbArgs += '--aencoder', 'copy'               # Passthrough without re-encoding
    $hbArgs += '--audio-copy-mask', 'aac,ac3,eac3,truehd,dts,dtshd,mp2,mp3,opus,flac'
    $hbArgs += '--audio-fallback', 'ac3'          # Re-encode to AC3 only if passthrough fails
    $hbArgs += '--keep-aname'                     # Preserve audio track names

    # ======================================
    # Subtitle Preservation
    # ======================================
    $hbArgs += '--all-subtitles'                  # Select every subtitle track
    $hbArgs += '--keep-subname'                   # Preserve subtitle track names

    # ======================================
    # Sync & Alignment
    # ======================================
    $hbArgs += '--align-av'                       # Align audio/video for proper sync

    return $hbArgs
}

# -------------------------------------------------
# Main function to process the HandBrake queue.
# -------------------------------------------------
function Invoke-HandBrakeQueue {
    param(
        [string]$CsvPath,
        [string]$HandBrakePath,
        [switch]$DebugCommands,
        [int]$QualityLevel = 22,
        [bool]$UseQSV = $true
    )

    $HandBrakePath = Get-HandBrakePath -Candidate $HandBrakePath
    Write-Host "Using HandBrakeCLI at: $HandBrakePath" -ForegroundColor Cyan

    $queue = Import-Queue -CsvPath $CsvPath
    $total = $queue.Count
    Write-Host "`nQueue contains $total entries." -ForegroundColor Yellow

    $statusFile = Join-Path $PSScriptRoot 'HandBrakeStatus.json'
    $status = Import-Status -StatusFile $statusFile

    $completed = $status.Completed
    $failed    = $status.Failed
    $skipped   = $status.Skipped
    $retried   = $status.Retried

    $pending = $queue | Where-Object { $completed -notcontains $_.SourceFile }
    $pendingCount = $pending.Count
    Write-Host "`n$pendingCount items still need processing." -ForegroundColor Cyan

    if ($pendingCount -eq 0) {
        Write-Host "No pending queue items. Nothing to do." -ForegroundColor Green
        return
    }

    $processed = 0
    $script:stopRequested = $false
    $conversions = New-Object System.Collections.ArrayList

    Register-EngineEvent PowerShell.Exiting -Action {
        $script:stopRequested = $true
    } | Out-Null

    foreach ($item in $pending) {
        if ($script:stopRequested) {
            Write-Host "`nStop requested – exiting cleanly…" -ForegroundColor Red
            break
        }

        $source = $item.SourceFile
        $sourceDir = Split-Path -Parent $source
        $sourceBaseName = [IO.Path]::GetFileNameWithoutExtension($source)
        $sourceExtension = [IO.Path]::GetExtension($source)
        $target = Join-Path $sourceDir "$sourceBaseName.mkv"
        $backup = Join-Path $sourceDir "$sourceBaseName`_bak$sourceExtension"
        $desiredCodec = if ($item.DesiredCodec) { $item.DesiredCodec } else { 'H.265' }
        $detectedCodec = $item.DetectedCodec
        $isRetry = $false

        # -------------------------------------------------
        # Guard clauses: Determine if we need to process this item
        # -------------------------------------------------
        
        # If both backup and target exist, conversion completed successfully in a previous run
        if ((Test-Path $backup -PathType Leaf) -and (Test-Path $target -PathType Leaf)) {
            Write-Host "✔ SKIPPED (already converted): $source → $target" -ForegroundColor DarkGray
            [void]$skipped.Add($source)
            Save-Status -StatusFile $statusFile -Completed $completed -Failed $failed -Skipped $skipped -Retried $retried
            $processed++
            continue
        }

        # If backup exists but target doesn't, the previous conversion failed partway through
        # Proceed to retry conversion from the backup
        if ((Test-Path $backup -PathType Leaf) -and -not (Test-Path $target -PathType Leaf)) {
            Write-Host "⚠ RETRYING (previous conversion failed): $backup" -ForegroundColor Yellow
            $isRetry = $true
            # Continue to conversion step below (don't rename source, use existing backup)
        }
        else {
            # Normal case: rename source to backup first
            # -------------------------------------------------
            # Step 1: Rename original file to backup
            # -------------------------------------------------
            Write-Host "`n[$($processed + 1)/$total] Preparing: $source" -ForegroundColor Green
            
            if (-not (Test-Path $source -PathType Leaf)) {
                Write-Host "✖ ERROR (source file not found): $source" -ForegroundColor Red
                [void]$failed.Add($source)
                Save-Status -StatusFile $statusFile -Completed $completed -Failed $failed -Skipped $skipped -Retried $retried
                $processed++
                continue
            }

            try {
                Rename-Item -Path $source -NewName $backup -Force | Out-Null
                Write-Host "    → Renamed to backup: $backup" -ForegroundColor Gray
            }
            catch {
                Write-Host "✖ FAILED to rename source to backup: $_" -ForegroundColor Red
                [void]$failed.Add($source)
                Save-Status -StatusFile $statusFile -Completed $completed -Failed $failed -Skipped $skipped -Retried $retried
                $processed++
                continue
            }
        }

        # ======================================
        # Step 2: Convert the backup to output
        # ======================================
        $hbArgs = Build-HandBrakeArguments -Source $backup -Target $target -DesiredCodec $desiredCodec -QualityLevel $QualityLevel -UseQSV $UseQSV

        $percent = [math]::Round((($processed + 1) / $total) * 100,0)
        Write-Progress -Activity "HandBrake transcoding" `
                       -Status "Processing: $([IO.Path]::GetFileName($source))" `
                       -PercentComplete $percent

        Write-Host "[$($processed + 1)/$total] CONVERTING: $backup" -ForegroundColor Green
        Write-Host "    → Output  : $target" -ForegroundColor Gray
        Write-Host "    → Encoder: $desiredCodec (detected $detectedCodec)" -ForegroundColor Gray

        # ======================================
        # Debug: Print the exact command if requested
        # ======================================
        if ($DebugCommands) {
            Write-Host "`n[DEBUG] HandBrakeCLI command:" -ForegroundColor Magenta
            Write-Host "  `"$HandBrakePath`" $($hbArgs -join ' ')" -ForegroundColor Cyan
            Write-Host ""
        }

        $processInfo = New-Object System.Diagnostics.ProcessStartInfo
        $processInfo.FileName = $HandBrakePath
        $processInfo.Arguments = $hbArgs -join ' '
        $processInfo.RedirectStandardOutput = $true
        $processInfo.RedirectStandardError = $true
        $processInfo.UseShellExecute = $false
        $processInfo.CreateNoWindow = $true

        $proc = [System.Diagnostics.Process]::Start($processInfo)
        
        # Read both streams asynchronously to avoid deadlock
        $stdOutTask = $proc.StandardOutput.ReadToEndAsync()
        $stdErrTask = $proc.StandardError.ReadToEndAsync()

        $proc.WaitForExit()

        $stdOut = $stdOutTask.Result
        $stdErr = $stdErrTask.Result

        if ($proc.ExitCode -eq 0) {
            # If conversion succeeded, we can optionally print the HandBrakeCLI output for debugging
            if ($debugCommands) {
                Write-Host "`n[DEBUG] HandBrakeCLI output:" -ForegroundColor Magenta
                Write-Host $stdOut -ForegroundColor Green
                if ($stdErr) {
                    Write-Host "`n[DEBUG] HandBrakeCLI error output:" -ForegroundColor Magenta
                    Write-Host $stdErr -ForegroundColor Red
                }
            }

            Write-Host "✔ COMPLETED: $target" -ForegroundColor Green
            
            # Track successful conversion for cleanup script
            [void]$conversions.Add([pscustomobject]@{
                BackupFile = $backup
                OutputFile = $target
            })
            
            # If this was a retry, track it separately
            if ($isRetry) {
                Write-Host "    ✓ Retry succeeded" -ForegroundColor Green
                [void]$retried.Add($source)
            }
            
            [void]$completed.Add($source)
        }
        else {
            Write-Host "✖ FAILED (exit $($proc.ExitCode)): Backup is preserved at $backup" -ForegroundColor Red
            Write-Host $stdErr -ForegroundColor DarkRed
            [void]$failed.Add($source)
        }

        Save-Status -StatusFile $statusFile -Completed $completed -Failed $failed -Skipped $skipped -Retried $retried
        $processed++
    }

    # Export conversions list for cleanup script
    $conversionFile = Join-Path $PSScriptRoot 'HandBrakeConversions.csv'
    Save-Conversions -ConversionsFile $conversionFile -Conversions $conversions

    Write-Host "`n=== HandBrake run finished ===" -ForegroundColor Cyan
    Write-Host "Total items   : $total"
    Write-Host "Processed     : $processed"
    Write-Host "Completed     : $($completed.Count)"
    Write-Host "  ├─ New conversions    : $($completed.Count - $retried.Count)"
    Write-Host "  └─ Retried & fixed    : $($retried.Count)" -ForegroundColor Green
    Write-Host "Failed        : $($failed.Count)"
    Write-Host "Skipped (already existed) : $($skipped.Count)" -ForegroundColor DarkGray
    Write-Host "`nYou can rerun the script at any time – it will automatically skip the entries recorded in HandBrakeStatus.json." -ForegroundColor Yellow
}


# -------------------------------------------------
# Entry point
# -------------------------------------------------

Set-StrictMode -Version Latest
Invoke-HandBrakeQueue -CsvPath $CsvPath -HandBrakePath $HandBrakePath -DebugCommands $DebugCommands -QualityLevel $QualityLevel -UseQSV $UseQSV
